version: "3.8"

services:
  mysql:
   image: mysql:latest
   environment:
    - MYSQL_DATABASE=tododb
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASSWORD=root
   expose:
     - "3306"
   volumes:
    - mysql-data:/var/lib/mysql
    - ./todoapp.sql:/docker-entrypoint-initdb.d/init.sql
  react-web:
    image: todoapp-react:latest
    ports:
      - "3000:3000"
    depends_on:
      - springboot-web
  springboot-web:
    image: todoapp-springboot:latest
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql:3306/tododb",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8088:8088"
    depends_on:
      - mysql
volumes:
  mysql-data:
      