version: '1'

services:
  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./todoapp.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    image: todoapp-spring
    ports:
      - "8005:8080"
    depends_on:
      - mysql
volumes:
  mysql-data